-- 現行Excel「（仮）NKC棚卸.xlsx」シート1 からの移行データ(docs/migration/*.csv より生成)
SET NAMES utf8mb4;

-- inventory_items: 109 rows
INSERT INTO inventory_items (id, item_code, item_name, management_type, category_id, condition_code, stock_type, customer_id, manufacturer, model_number, serial_number, network_info, location_id, notes, is_active, sort_order, created_at, updated_at, created_by, updated_by, source_excel_rows) VALUES
(1, 'ITEM-000001', 'デスクトップ本体', 'unit', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 1, NOW(), NOW(), 'excel_import', 'excel_import', '4;5'),
(2, 'ITEM-000002', 'ファン', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 2, NOW(), NOW(), 'excel_import', 'excel_import', '6'),
(3, 'ITEM-000003', '有線マウス', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, 'ラック上から2段目一番右のかご', 1, 3, NOW(), NOW(), 'excel_import', 'excel_import', '7'),
(4, 'ITEM-000004', '有線マウス', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 4, NOW(), NOW(), 'excel_import', 'excel_import', '8'),
(5, 'ITEM-000005', '無線マウス', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 5, NOW(), NOW(), 'excel_import', 'excel_import', '9'),
(6, 'ITEM-000006', '無線マウス', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 6, NOW(), NOW(), 'excel_import', 'excel_import', '10'),
(7, 'ITEM-000007', 'BUFFALO PortableHD', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 7, NOW(), NOW(), 'excel_import', 'excel_import', '11'),
(8, 'ITEM-000008', 'CD-R', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 8, NOW(), NOW(), 'excel_import', 'excel_import', '12'),
(9, 'ITEM-000009', 'CD-R', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 9, NOW(), NOW(), 'excel_import', 'excel_import', '13'),
(10, 'ITEM-000010', 'NFC/Felicaリーダー', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 10, NOW(), NOW(), 'excel_import', 'excel_import', '14'),
(11, 'ITEM-000011', 'NFC/Felicaリーダー', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 11, NOW(), NOW(), 'excel_import', 'excel_import', '15'),
(12, 'ITEM-000012', '外付けテンキー', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 12, NOW(), NOW(), 'excel_import', 'excel_import', '16'),
(13, 'ITEM-000013', '外付けDVDリーダー', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 13, NOW(), NOW(), 'excel_import', 'excel_import', '17'),
(14, 'ITEM-000014', 'HDD', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 14, NOW(), NOW(), 'excel_import', 'excel_import', '18'),
(15, 'ITEM-000015', 'A to Bケーブル', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 15, NOW(), NOW(), 'excel_import', 'excel_import', '19'),
(16, 'ITEM-000016', 'LAN→変換', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 16, NOW(), NOW(), 'excel_import', 'excel_import', '20'),
(17, 'ITEM-000017', '骨伝導イヤホン', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 17, NOW(), NOW(), 'excel_import', 'excel_import', '21'),
(18, 'ITEM-000018', 'A to Cケーブル', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 18, NOW(), NOW(), 'excel_import', 'excel_import', '22'),
(19, 'ITEM-000019', 'microSD→SD変換', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 19, NOW(), NOW(), 'excel_import', 'excel_import', '23'),
(20, 'ITEM-000020', '切り替え器', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, '4台接続可能', 1, 20, NOW(), NOW(), 'excel_import', 'excel_import', '24'),
(21, 'ITEM-000021', 'Anker PowerExpand+7-in1 USB-C PD イーサネット ハブ', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 2, NULL, 1, 21, NOW(), NOW(), 'excel_import', 'excel_import', '25'),
(22, 'ITEM-000022', 'クローンＨＤＤスタンド', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 22, NOW(), NOW(), 'excel_import', 'excel_import', '26'),
(23, 'ITEM-000023', 'BUFFALO　ポータブルハードディスク', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 23, NOW(), NOW(), 'excel_import', 'excel_import', '27'),
(24, 'ITEM-000024', 'I-O DATA SSD', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 24, NOW(), NOW(), 'excel_import', 'excel_import', '28'),
(25, 'ITEM-000025', 'デジタルテスター', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 25, NOW(), NOW(), 'excel_import', 'excel_import', '29'),
(26, 'ITEM-000026', 'ＬＡＮケーブルテスター', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 26, NOW(), NOW(), 'excel_import', 'excel_import', '30'),
(27, 'ITEM-000027', 'TP-link 無線ＬＡＮルーター', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 27, NOW(), NOW(), 'excel_import', 'excel_import', '31'),
(28, 'ITEM-000028', 'テスター棒用ワニ口クリップ', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 28, NOW(), NOW(), 'excel_import', 'excel_import', '32'),
(29, 'ITEM-000029', 'スピーカーみたいなマイク', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 3, NULL, 1, 29, NOW(), NOW(), 'excel_import', 'excel_import', '33'),
(30, 'ITEM-000030', '恵会眠りSCAN用無線ＡＰ予備', 'unit', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 4, NULL, 1, 30, NOW(), NOW(), 'excel_import', 'excel_import', '34;35'),
(31, 'ITEM-000031', '恵会眠りSCAN用PoEスイッチラック固定用あまり', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 4, NULL, 1, 31, NOW(), NOW(), 'excel_import', 'excel_import', '36'),
(32, 'ITEM-000032', 'Latitude 5490 交換済みバッテリー', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 4, NULL, 1, 32, NOW(), NOW(), 'excel_import', 'excel_import', '37'),
(33, 'ITEM-000033', '中継器', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 4, '永和会から回収したもの', 1, 33, NOW(), NOW(), 'excel_import', 'excel_import', '38'),
(34, 'ITEM-000034', '8口HUB', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 34, NOW(), NOW(), 'excel_import', 'excel_import', '39'),
(35, 'ITEM-000035', '8口HUB', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 35, NOW(), NOW(), 'excel_import', 'excel_import', '40'),
(36, 'ITEM-000036', '5口HUB', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 36, NOW(), NOW(), 'excel_import', 'excel_import', '41'),
(37, 'ITEM-000037', '5口HUB', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 37, NOW(), NOW(), 'excel_import', 'excel_import', '42'),
(38, 'ITEM-000038', 'エンビパイプカッター', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 38, NOW(), NOW(), 'excel_import', 'excel_import', '43'),
(39, 'ITEM-000039', 'REMOTE CABLE TESTER', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 39, NOW(), NOW(), 'excel_import', 'excel_import', '44'),
(40, 'ITEM-000040', 'LANケーブル　先の部分（青）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 40, NOW(), NOW(), 'excel_import', 'excel_import', '45'),
(41, 'ITEM-000041', 'LANケーブル　先の部分（透明）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 41, NOW(), NOW(), 'excel_import', 'excel_import', '46'),
(42, 'ITEM-000042', 'LANケーブルカッター', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 5, NULL, 1, 42, NOW(), NOW(), 'excel_import', 'excel_import', '47'),
(43, 'ITEM-000043', 'I-O DATA ディスプレイモニター', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 6, NULL, 1, 43, NOW(), NOW(), 'excel_import', 'excel_import', '48'),
(44, 'ITEM-000044', 'WiFi Access Point（Meraki）', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 7, NULL, 1, 44, NOW(), NOW(), 'excel_import', 'excel_import', '49'),
(45, 'ITEM-000045', 'Magic Keybord（小）', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 7, NULL, 1, 45, NOW(), NOW(), 'excel_import', 'excel_import', '50'),
(46, 'ITEM-000046', 'Magic Keybord（大）', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 7, NULL, 1, 46, NOW(), NOW(), 'excel_import', 'excel_import', '51'),
(47, 'ITEM-000047', '無線キーボート（MagicKeybord除く）', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 7, '不良（キーボード外れ）１台あり', 1, 47, NOW(), NOW(), 'excel_import', 'excel_import', '52'),
(48, 'ITEM-000048', 'Meraki 備品セット', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 7, NULL, 1, 48, NOW(), NOW(), 'excel_import', 'excel_import', '53'),
(49, 'ITEM-000049', '有線キーボード', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 7, NULL, 1, 49, NOW(), NOW(), 'excel_import', 'excel_import', '54'),
(50, 'ITEM-000050', '有線キーボード', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 7, NULL, 1, 50, NOW(), NOW(), 'excel_import', 'excel_import', '55'),
(51, 'ITEM-000051', 'Meraki Go電源ケーブル', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 7, 'PoEのもので使用しないため10→2に減らす　2025.12.26', 1, 51, NOW(), NOW(), 'excel_import', 'excel_import', '56'),
(52, 'ITEM-000052', 'ケーブル配線保護カバー（LEOCASLET）', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 8, NULL, 1, 52, NOW(), NOW(), 'excel_import', 'excel_import', '57'),
(53, 'ITEM-000053', 'ケーブルカバー（Hiding Cables）', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 8, NULL, 1, 53, NOW(), NOW(), 'excel_import', 'excel_import', '58'),
(54, 'ITEM-000054', '配線カバーマジックテープ', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 8, NULL, 1, 54, NOW(), NOW(), 'excel_import', 'excel_import', '59'),
(55, 'ITEM-000055', 'SSDケース（AOTECH）', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 55, NOW(), NOW(), 'excel_import', 'excel_import', '60'),
(56, 'ITEM-000056', 'mac mini', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 56, NOW(), NOW(), 'excel_import', 'excel_import', '61'),
(57, 'ITEM-000057', '一体型デスクトップ', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 57, NOW(), NOW(), 'excel_import', 'excel_import', '62'),
(58, 'ITEM-000058', 'スキャンスナップＳ300', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 58, NOW(), NOW(), 'excel_import', 'excel_import', '63'),
(59, 'ITEM-000059', 'ＡＴＫ電源ユニット（保証書類のみ）', 'unit', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 59, NOW(), NOW(), 'excel_import', 'excel_import', '64'),
(60, 'ITEM-000060', 'プロジェクターＧＤＰ１Ｗ', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 60, NOW(), NOW(), 'excel_import', 'excel_import', '65'),
(61, 'ITEM-000061', 'プロジェクター布', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 61, NOW(), NOW(), 'excel_import', 'excel_import', '66'),
(62, 'ITEM-000062', 'mac book Air', 'unit', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 1, '20260916　森　　在庫棚', 1, 62, NOW(), NOW(), 'excel_import', 'excel_import', '67'),
(63, 'ITEM-000063', 'HDMI', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, 9, NULL, 1, 63, NOW(), NOW(), 'excel_import', 'excel_import', '68'),
(64, 'ITEM-000064', 'LANケーブル(大)', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 64, NOW(), NOW(), 'excel_import', 'excel_import', '69'),
(65, 'ITEM-000065', 'LANケーブル(小)', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 65, NOW(), NOW(), 'excel_import', 'excel_import', '70'),
(66, 'ITEM-000066', 'Displayケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 66, NOW(), NOW(), 'excel_import', 'excel_import', '71'),
(67, 'ITEM-000067', 'Display電源ケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 67, NOW(), NOW(), 'excel_import', 'excel_import', '72'),
(68, 'ITEM-000068', NULL, 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 68, NOW(), NOW(), 'excel_import', 'excel_import', '73'),
(69, 'ITEM-000069', 'Cタイプケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 69, NOW(), NOW(), 'excel_import', 'excel_import', '74'),
(70, 'ITEM-000070', 'USB C タイプケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 70, NOW(), NOW(), 'excel_import', 'excel_import', '75'),
(71, 'ITEM-000071', 'ノート電源ケーブルNEC', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 71, NOW(), NOW(), 'excel_import', 'excel_import', '76'),
(72, 'ITEM-000072', 'アナログケーブル　USB', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 72, NOW(), NOW(), 'excel_import', 'excel_import', '77'),
(73, 'ITEM-000073', '延長ケーブル(4口)', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, '大村さんの机で使用中(設定作業の電源口数を増やすため)', 1, 73, NOW(), NOW(), 'excel_import', 'excel_import', '78'),
(74, 'ITEM-000074', '延長ケーブル(6口)', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 74, NOW(), NOW(), 'excel_import', 'excel_import', '79'),
(75, 'ITEM-000075', '延長ケーブル(7口)', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 75, NOW(), NOW(), 'excel_import', 'excel_import', '80'),
(76, 'ITEM-000076', '延長ケーブル(10口)', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 76, NOW(), NOW(), 'excel_import', 'excel_import', '81'),
(77, 'ITEM-000077', '延長ケーブル(10口)', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 77, NOW(), NOW(), 'excel_import', 'excel_import', '82'),
(78, 'ITEM-000078', 'IEC電源タップ(4口)', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 78, NOW(), NOW(), 'excel_import', 'excel_import', '83'),
(79, 'ITEM-000079', 'デジタル to デジタルケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 79, NOW(), NOW(), 'excel_import', 'excel_import', '84'),
(80, 'ITEM-000080', '音声ケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 80, NOW(), NOW(), 'excel_import', 'excel_import', '85'),
(81, 'ITEM-000081', '電話線', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 81, NOW(), NOW(), 'excel_import', 'excel_import', '86'),
(82, 'ITEM-000082', '電話線アダプタ', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 82, NOW(), NOW(), 'excel_import', 'excel_import', '87'),
(83, 'ITEM-000083', '電話　分配ケーブル', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 83, NOW(), NOW(), 'excel_import', 'excel_import', '88'),
(84, 'ITEM-000084', '三口変換コネクタ', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 84, NOW(), NOW(), 'excel_import', 'excel_import', '89'),
(85, 'ITEM-000085', 'ノート電源ケーブルPhilips', 'quantity', NULL, NULL, 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 85, NOW(), NOW(), 'excel_import', 'excel_import', '90'),
(86, 'ITEM-000086', 'Displayケーブル to HDMI　変換ケーブル', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 86, NOW(), NOW(), 'excel_import', 'excel_import', '91'),
(87, 'ITEM-000087', 'ヘッドセット', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 10, 'スペシャルマッチ等で使用', 1, 87, NOW(), NOW(), 'excel_import', 'excel_import', '92'),
(88, 'ITEM-000088', 'マウス（Lenovo）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 11, '永和会様PC仕入時の特典', 1, 88, NOW(), NOW(), 'excel_import', 'excel_import', '93'),
(89, 'ITEM-000089', 'マウス（Lenovo）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 11, '腎愛会様PC仕入時の特典', 1, 89, NOW(), NOW(), 'excel_import', 'excel_import', '94'),
(90, 'ITEM-000090', 'キーボード（Ｄｅｌｌ）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 12, '腎愛会様PC仕入時の特典', 1, 90, NOW(), NOW(), 'excel_import', 'excel_import', '95'),
(91, 'ITEM-000091', 'マウス（NEC）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 11, '腎愛会様PC仕入時の特典', 1, 91, NOW(), NOW(), 'excel_import', 'excel_import', '96'),
(92, 'ITEM-000092', 'キーボード（NEC）', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, 12, '腎愛会様PC仕入時の特典', 1, 92, NOW(), NOW(), 'excel_import', 'excel_import', '97'),
(93, 'ITEM-000093', '無線ルーター（buffalo', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, 11, 'エミフル様機器入替分', 1, 93, NOW(), NOW(), 'excel_import', 'excel_import', '98'),
(94, 'ITEM-000094', 'Display to Mini Display', 'quantity', NULL, 'new', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, 'ディスプレイ端子⇔ミニディスプレイ端子\n井上新規記載【70のDisplayケーブルのこと？】', 1, 94, NOW(), NOW(), 'excel_import', 'excel_import', '99'),
(95, 'ITEM-000095', 'USB B タイプケーブル', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, '井上新規記載', 1, 95, NOW(), NOW(), 'excel_import', 'excel_import', '100'),
(96, 'ITEM-000096', 'USBーA延長', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, '井上新規記載', 1, 96, NOW(), NOW(), 'excel_import', 'excel_import', '101'),
(97, 'ITEM-000097', 'Cタイプケ変換', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 97, NOW(), NOW(), 'excel_import', 'excel_import', '102'),
(98, 'ITEM-000098', 'ACアダプタ：TOSHIBA PA3755U', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 98, NOW(), NOW(), 'excel_import', 'excel_import', '103'),
(99, 'ITEM-000099', 'ACアダプタ：TOSHIBA PA3714U', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 99, NOW(), NOW(), 'excel_import', 'excel_import', '104'),
(100, 'ITEM-000100', 'ACアダプタ：HYT-1207000', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 100, NOW(), NOW(), 'excel_import', 'excel_import', '105'),
(101, 'ITEM-000101', 'ACアダプタ：DEL HKA65NM201', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 101, NOW(), NOW(), 'excel_import', 'excel_import', '106'),
(102, 'ITEM-000102', 'ACアダプタ：DEL HA65NS5-00', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 102, NOW(), NOW(), 'excel_import', 'excel_import', '107'),
(103, 'ITEM-000103', 'ACアダプタ：DEL LA45NN140', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 103, NOW(), NOW(), 'excel_import', 'excel_import', '108'),
(104, 'ITEM-000104', 'ACアダプタ：ELECTRONICS', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 104, NOW(), NOW(), 'excel_import', 'excel_import', '109'),
(105, 'ITEM-000105', 'ACアダプタ：Lenovo ADLX45NCC2A', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 105, NOW(), NOW(), 'excel_import', 'excel_import', '110'),
(106, 'ITEM-000106', 'ACアダプタ：A12-040N2A', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 106, NOW(), NOW(), 'excel_import', 'excel_import', '111'),
(107, 'ITEM-000107', 'ACアダプタ：Canon K30359', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 107, NOW(), NOW(), 'excel_import', 'excel_import', '112'),
(108, 'ITEM-000108', 'ACアダプタ：J651-1903420DI', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 108, NOW(), NOW(), 'excel_import', 'excel_import', '113'),
(109, 'ITEM-000109', 'ハードディスクケース', 'quantity', NULL, 'used', 'internal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 109, NOW(), NOW(), 'excel_import', 'excel_import', '114');

-- inventory_units: 6 rows
INSERT INTO inventory_units (id, item_id, management_no, serial_number, ip_address, status, location_id, notes, is_active, created_at, updated_at, created_by, updated_by, source_excel_row) VALUES
(1, 1, 'NKC：0006', NULL, NULL, 'in_stock', 1, NULL, 1, NOW(), NOW(), 'excel_import', 'excel_import', 4),
(2, 1, 'NKC：0002', NULL, NULL, 'in_stock', 1, NULL, 1, NOW(), NOW(), 'excel_import', 'excel_import', 5),
(3, 30, '238', NULL, NULL, 'in_stock', 4, NULL, 1, NOW(), NOW(), 'excel_import', 'excel_import', 34),
(4, 30, '239', NULL, NULL, 'in_stock', 4, NULL, 1, NOW(), NOW(), 'excel_import', 'excel_import', 35),
(5, 59, 'NKC002', NULL, NULL, 'in_stock', 1, NULL, 1, NOW(), NOW(), 'excel_import', 'excel_import', 64),
(6, 62, 'NKC-OZAKI', NULL, NULL, 'in_stock', 1, NULL, 1, NOW(), NOW(), 'excel_import', 'excel_import', 67);

-- inventory_counts: 2 rows
INSERT INTO inventory_counts (id, count_name, base_date, count_period, entry_date, start_date, end_date, status, notes, created_by, created_at, confirmed_by, confirmed_at) VALUES
(1, '2025/12/26 棚卸', '2025-12-26', NULL, NULL, NULL, NULL, 'confirmed', 'Excel シート1 F列「棚卸数」より移行', 'excel_import', NOW(), 'excel_import', NOW()),
(2, '2026/1/6 棚卸', '2026-01-06', '2025/12/26', '2026-01-08', NULL, NULL, 'confirmed', 'Excel シート1 G列「棚卸数 2026/1/6」より移行', 'excel_import', NOW(), 'excel_import', NOW());

-- inventory_count_details: 160 rows
INSERT INTO inventory_count_details (id, count_id, item_id, count_quantity, confirm_status, location_id_at_count, counted_by, counted_at, notes, created_at, updated_at, created_by, updated_by, source_excel_rows) VALUES
(1, 1, 1, 2, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '4;5'),
(2, 1, 2, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '6'),
(3, 1, 3, 3, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '7'),
(4, 1, 4, 2, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '8'),
(5, 1, 5, 5, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '9'),
(6, 1, 6, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '10'),
(7, 1, 7, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '11'),
(8, 1, 8, 2, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '12'),
(9, 1, 9, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '13'),
(10, 1, 10, 2, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '14'),
(11, 1, 12, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '16'),
(12, 1, 13, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '17'),
(13, 1, 14, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '18'),
(14, 1, 15, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '19'),
(15, 1, 16, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '20'),
(16, 1, 17, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '21'),
(17, 1, 18, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '22'),
(18, 1, 19, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '23'),
(19, 1, 20, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '24'),
(20, 1, 21, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '25'),
(21, 1, 22, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '26'),
(22, 1, 23, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '27'),
(23, 1, 24, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '28'),
(24, 1, 25, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '29'),
(25, 1, 26, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '30'),
(26, 1, 27, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '31'),
(27, 1, 28, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '32'),
(28, 1, 29, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '33'),
(29, 1, 30, 2, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '34;35'),
(30, 1, 31, 1, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '36'),
(31, 1, 32, 1, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '37'),
(32, 1, 33, 1, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '38'),
(33, 1, 34, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '39'),
(34, 1, 35, 2, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '40'),
(35, 1, 36, 3, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '41'),
(36, 1, 37, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '42'),
(37, 1, 38, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '43'),
(38, 1, 39, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '44'),
(39, 1, 40, 38, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '45'),
(40, 1, 41, 89, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '46'),
(41, 1, 42, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '47'),
(42, 1, 43, 1, 'confirmed', 6, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '48'),
(43, 1, 44, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '49'),
(44, 1, 45, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '50'),
(45, 1, 46, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '51'),
(46, 1, 47, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '52'),
(47, 1, 48, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '53'),
(48, 1, 49, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '54'),
(49, 1, 50, 2, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '55'),
(50, 1, 51, 2, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '56'),
(51, 1, 52, 5, 'confirmed', 8, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '57'),
(52, 1, 53, 3, 'confirmed', 8, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '58'),
(53, 1, 54, 2, 'confirmed', 8, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '59'),
(54, 1, 55, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '60'),
(55, 1, 56, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '61'),
(56, 1, 57, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '62'),
(57, 1, 58, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '63'),
(58, 1, 59, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '64'),
(59, 1, 60, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '65'),
(60, 1, 61, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '66'),
(61, 1, 62, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '67'),
(62, 1, 63, 21, 'confirmed', 9, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '68'),
(63, 1, 64, 16, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '69'),
(64, 1, 65, 25, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '70'),
(65, 1, 66, 10, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '71'),
(66, 1, 67, 5, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '72'),
(67, 1, 68, 2, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '73'),
(68, 1, 69, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '74'),
(69, 1, 70, 2, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '75'),
(70, 1, 71, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '76'),
(71, 1, 72, 4, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '77'),
(72, 1, 73, 0, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '78'),
(73, 1, 74, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '79'),
(74, 1, 76, 3, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '81'),
(75, 1, 77, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '82'),
(76, 1, 78, 3, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '83'),
(77, 1, 79, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '84'),
(78, 1, 80, 5, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '85'),
(79, 1, 81, 11, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '86'),
(80, 1, 84, 11, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '89'),
(81, 1, 85, 0, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '90'),
(82, 1, 86, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '91'),
(83, 1, 87, 5, 'confirmed', 10, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '92'),
(84, 1, 88, 28, 'confirmed', 11, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '93'),
(85, 1, 89, 3, 'confirmed', 11, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '94'),
(86, 1, 90, 3, 'confirmed', 12, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '95'),
(87, 1, 91, 3, 'confirmed', 11, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '96'),
(88, 1, 92, 3, 'confirmed', 12, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '97'),
(89, 1, 93, 1, 'confirmed', 11, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '98'),
(90, 1, 94, 19, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '99'),
(91, 1, 95, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '100'),
(92, 1, 96, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '101'),
(93, 2, 3, 6, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '7'),
(94, 2, 4, 4, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '8'),
(95, 2, 5, 4, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '9'),
(96, 2, 6, 3, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '10'),
(97, 2, 8, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '12'),
(98, 2, 9, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '13'),
(99, 2, 11, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '15'),
(100, 2, 12, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '16'),
(101, 2, 13, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '17'),
(102, 2, 14, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '18'),
(103, 2, 20, 1, 'confirmed', 2, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '24'),
(104, 2, 22, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '26'),
(105, 2, 25, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '29'),
(106, 2, 26, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '30'),
(107, 2, 27, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '31'),
(108, 2, 28, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '32'),
(109, 2, 29, 1, 'confirmed', 3, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '33'),
(110, 2, 30, 2, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '34;35'),
(111, 2, 31, 1, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '36'),
(112, 2, 32, 1, 'confirmed', 4, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '37'),
(113, 2, 34, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '39'),
(114, 2, 35, 4, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '40'),
(115, 2, 36, 2, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '41'),
(116, 2, 37, 4, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '42'),
(117, 2, 38, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '43'),
(118, 2, 39, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '44'),
(119, 2, 42, 1, 'confirmed', 5, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '47'),
(120, 2, 47, 6, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '52'),
(121, 2, 48, 1, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '53'),
(122, 2, 49, 17, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '54'),
(123, 2, 50, 3, 'confirmed', 7, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '55'),
(124, 2, 53, 3, 'confirmed', 8, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '58'),
(125, 2, 54, 2, 'confirmed', 8, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '59'),
(126, 2, 55, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '60'),
(127, 2, 56, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '61'),
(128, 2, 58, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '63'),
(129, 2, 60, 1, 'confirmed', 1, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '65'),
(130, 2, 63, 4, 'confirmed', 9, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '68'),
(131, 2, 64, 25, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '69'),
(132, 2, 65, 22, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '70'),
(133, 2, 67, 13, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '72'),
(134, 2, 69, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '74'),
(135, 2, 72, 5, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '77'),
(136, 2, 73, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '78'),
(137, 2, 75, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '80'),
(138, 2, 76, 3, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '81'),
(139, 2, 77, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '82'),
(140, 2, 78, 3, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '83'),
(141, 2, 80, 4, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '85'),
(142, 2, 81, 10, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '86'),
(143, 2, 82, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '87'),
(144, 2, 83, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '88'),
(145, 2, 84, 14, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '89'),
(146, 2, 87, 5, 'confirmed', 10, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '92'),
(147, 2, 94, 19, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '99'),
(148, 2, 97, 5, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '102'),
(149, 2, 98, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '103'),
(150, 2, 99, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '104'),
(151, 2, 100, 8, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '105'),
(152, 2, 101, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '106'),
(153, 2, 102, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '107'),
(154, 2, 103, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '108'),
(155, 2, 104, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '109'),
(156, 2, 105, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '110'),
(157, 2, 106, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '111'),
(158, 2, 107, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '112'),
(159, 2, 108, 1, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '113'),
(160, 2, 109, 6, 'confirmed', NULL, NULL, NULL, NULL, NOW(), NOW(), 'excel_import', 'excel_import', '114');

-- inventory_count_unit_results: 8 rows
INSERT INTO inventory_count_unit_results (id, count_id, unit_id, result, notes, created_at, updated_at, created_by, updated_by, source_excel_row) VALUES
(1, 1, 1, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 4),
(2, 1, 2, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 5),
(3, 1, 3, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 34),
(4, 1, 4, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 35),
(5, 1, 5, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 64),
(6, 1, 6, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 67),
(7, 2, 3, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 34),
(8, 2, 4, 'present', NULL, NOW(), NOW(), 'excel_import', 'excel_import', 35);

